const express = require('express')
const rumahSakitRouter = require('./routes/rumah-sakit')
const userRouter = require('./routes/user')
const pesanRouter = require('./routes/pesan')
const bodyParser = require('body-parser')
const app = express()
const port = 5000
const connection = require('./db/connection.js')
const User = require('./models/user.js')
const Pesan = require('./models/pesan.js')
const RumahSakit = require('./models/rumah-sakit.js')
const dotenv = require('dotenv')
dotenv.config()
User.sync({force:false})
RumahSakit.sync({force:false})
Pesan.sync({force:false})
app.use(express.json())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(rumahSakitRouter)
app.use(userRouter)
app.use(pesanRouter)

app.get('/', (req, res) => res.status(200).json({message:'hello world'}))

app.listen(process.env.PORT, () => {
    console.log('server running')
    connection()
})
